'use strict'

Timeline = (id, duration) ->
    if id == null
        throw new Exception('id argument is mandatory')
    if duration == null
        throw new Exception('duration argument is mandatory')
    @duration = duration
    @id = id
    @_render()
    return

Timeline::setTimeStartEnd = (timeStart, timeEnd) ->
    @timeStart = timeStart
    @timeEnd = timeEnd
    @updateBar()
    return

Timeline::setTimeStart = (timeStart) ->
    @timeStart = timeStart
    @updateBar()
    return

Timeline::setTimeEnd = (timeEnd) ->
    @timeEnd = timeEnd
    @updateBar()
    return

Timeline::remove = ->
    if @el
        @el.parentNode.removeChild @el
    return

Timeline::updateId = (id) ->
    @id = id
    @_render()
    @updateBar()
    return

Timeline::updateBar = ->
    x = 100 * @timeStart / @duration
    w = 100 * (@timeEnd - (@timeStart)) / @duration
    @el.style.left = x + '%'
    @el.style.width = w + '%'
    return

Timeline::_template = (data) ->
    '<div id="' + data.id + '" class="' + data.className + '"></div>'

Timeline::_render = ->
    if !@parentElement
        @parentElement = document.querySelector(@parentSelector)
    node = document.createElement('div')
    node.innerHTML = @_template(this)
    @parentElement.appendChild node.firstChild
    @el = document.getElementById(@id)
    return

Timeline::className = 'sample-selection-bar'
Timeline::parentSelector = '#selection-bar-back'
module.exports = Timeline

# ---
# generated by js2coffee 2.2.0