# This script was automatically generated by 'class_py2coffee' from Python class Asset
# 2017-07-30 05:46:10

class Asset
    constructor: () ->
        @guid = "00000000-0000-0000-0000-000000000000"
        @name = null  # None
        @ctime = null  # None
        @mtime = null  # None
        @mediaFiles = []
        @videoStreams = []
        @audioStreams = []
        @subStreams = []
        @proxyId = null  # None
        @programId = null  # None
