# This script was automatically generated by 'class_py2coffee' from Python class Asset
# 2017-10-26 08:27:05

class Asset_SubStream_Sync
    constructor: () ->
        @unmentioned = {}
        @offset1 = null  # None
        @offset2 = null  # None
        @delay1 = null  # None
        @delay2 = null  # None


class Asset_SubStream
    constructor: () ->
        @unmentioned = {}
        @type = null  # None
        @layout = null  # None
        @channels = []
        @language = null  # None
        @program_in = null  # None
        @program_out = null  # None
        @sync = {}
        @collector = "00000000-0000-0000-0000-000000000000"


class Asset_AudioStream_Sync
    constructor: () ->
        @unmentioned = {}
        @offset1 = null  # None
        @offset2 = null  # None
        @delay1 = null  # None
        @delay2 = null  # None


class Asset_AudioStream
    constructor: () ->
        @unmentioned = {}
        @type = null  # None
        @layout = null  # None
        @channels = []
        @language = null  # None
        @program_in = null  # None
        @program_out = null  # None
        @sync = {}
        @collector = "00000000-0000-0000-0000-000000000000"


class Asset_VideoStream_Cropdetect
    constructor: () ->
        @unmentioned = {}
        @w = null  # None
        @h = null  # None
        @x = null  # None
        @y = null  # None
        @sar = null  # None
        @aspect = null  # None


class Asset_VideoStream_Sync
    constructor: () ->
        @unmentioned = {}
        @offset1 = null  # None
        @offset2 = null  # None
        @delay1 = null  # None
        @delay2 = null  # None


class Asset_VideoStream
    constructor: () ->
        @unmentioned = {}
        @type = null  # None
        @layout = null  # None
        @channels = []
        @language = null  # None
        @program_in = null  # None
        @program_out = null  # None
        @sync = {}
        @collector = "00000000-0000-0000-0000-000000000000"
        @cropdetect = {}
        @fpsOriginal = "1:1"
        @fpsEncode = "1:1"


class Asset
    constructor: () ->
        @unmentioned = {}
        @guid = "00000000-0000-0000-0000-000000000000"
        @name = null  # None
        @ctime = null  # None
        @mtime = null  # None
        @mediaFiles = []
        @mediaFilesExtra = []
        @videoStreams = []
        @audioStreams = []
        @subStreams = []
        @proxyId = "00000000-0000-0000-0000-000000000000"
        @programId = "00000000-0000-0000-0000-000000000000"
        @programName = ""
