# This script was automatically generated by 'class_py2coffee' from Python class Asset
# 2017-08-24 15:51:30

class Asset_SubStream
    constructor: () ->
        @type = null  # None
        @layout = null  # None
        @channels = []
        @language = null  # None
        @program_in = null  # None
        @program_out = null  # None


class Asset_AudioStream
    constructor: () ->
        @type = null  # None
        @layout = null  # None
        @channels = []
        @language = null  # None
        @program_in = null  # None
        @program_out = null  # None


class Asset_VideoStream_Cropdetect
    constructor: () ->
        @w = null  # None
        @h = null  # None
        @x = null  # None
        @y = null  # None
        @sar = null  # None
        @aspect = null  # None


class Asset_VideoStream
    constructor: () ->
        @type = null  # None
        @layout = null  # None
        @channels = []
        @language = null  # None
        @program_in = null  # None
        @program_out = null  # None
        @cropdetect = {}


class Asset
    constructor: () ->
        @guid = "00000000-0000-0000-0000-000000000000"
        @name = null  # None
        @ctime = null  # None
        @mtime = null  # None
        @mediaFiles = []
        @videoStreams = []
        @audioStreams = []
        @subStreams = []
        @proxyId = "00000000-0000-0000-0000-000000000000"
        @programId = "00000000-0000-0000-0000-000000000000"
