# This script was automatically generated by 'class_py2coffee' from Python class Fileset
# 2017-11-16 09:18:33

class Fileset_File
    constructor: () ->
        @name = null  # None
        @ctime = null  # None
        @mtime = null  # None


class Fileset
    constructor: () ->
        @guid = "00000000-0000-0000-0000-000000000000"
        @name = null  # None
        @ctime = null  # None
        @mtime = null  # None
        @status = 0
        @server_path = null  # None
        @files = []
        @dirs = []
        @creation_time = 0
        @modification_time = 0
