# This script was automatically generated by 'class_py2coffee' from Python class Interaction
# 2017-10-26 08:27:05

class Interaction
    constructor: () ->
        @unmentioned = {}
        @guid = "00000000-0000-0000-0000-000000000000"
        @name = null  # None
        @ctime = null  # None
        @mtime = null  # None
        @status = 1
        @assetIn = "00000000-0000-0000-0000-000000000000"
        @assetOut = "00000000-0000-0000-0000-000000000000"
        @priority = 0
